"""Maintain Git LFS paths using a strict 100 MiB content threshold."""

import argparse
import json
from pathlib import Path
import re
import subprocess


THRESHOLD = 100 * 1024 * 1024
HEADER = "# Git LFS stores files larger than 100 MiB.\n# Generated by python scripts/lfs_policy.py sync.\n"
POINTER = re.compile(rb"version https://git-lfs.github.com/spec/v1\n(?:.*\n)*oid sha256:[0-9a-f]{64}\nsize ([0-9]+)\n")
HOOK = '#!/bin/sh\nexec python scripts/lfs_policy.py check\n'


class Repository:
    def __init__(self, directory):
        self.root = Path(subprocess.check_output(
            ["git", "rev-parse", "--show-toplevel"], cwd=directory,
            text=True,
        ).strip())

    def git(self, *arguments, data=None):
        return subprocess.check_output(
            ["git", *arguments], cwd=self.root, input=data,
        )

    def retrieve_files(self):
        entries = []
        for entry in self.git("ls-files", "--stage", "-z").split(b"\0"):
            if entry:
                metadata, name = entry.split(b"\t", 1)
                mode, object_id, stage = metadata.split()
                if stage != b"0":
                    raise ValueError("Resolve staged merge conflicts before applying the LFS policy.")
                if mode in (b"100644", b"100755"):
                    entries.append((name.decode("utf-8"), object_id))
        object_ids = list(dict.fromkeys(object_id for _, object_id in entries))
        sizes = {}
        if object_ids:
            output = self.git("cat-file", "--batch-check", data=b"\n".join(object_ids) + b"\n")
            for line in output.splitlines():
                object_id, _, size = line.split()
                sizes[object_id] = int(size)
        small = [object_id for object_id, size in sizes.items() if size < 1024]
        pointers = {}
        if small:
            output = self.git("cat-file", "--batch", data=b"\n".join(small) + b"\n")
            position = 0
            for object_id in small:
                position = output.index(b"\n", position) + 1
                content = output[position:position + sizes[object_id]]
                position += sizes[object_id] + 1
                match = POINTER.fullmatch(content)
                if match:
                    pointers[object_id] = int(match[1])
        return [
            (name, pointers.get(object_id, sizes[object_id]), object_id in pointers)
            for name, object_id in entries
        ]


class LfsPolicy:
    def __init__(self, repository):
        self.repository = repository

    def retrieve_attributes(self, files):
        lines = [HEADER]
        for name, size, _ in sorted(files):
            if size > THRESHOLD:
                # Quote whitespace and escape Git attribute pattern metacharacters.
                pattern = "/" + re.sub(r"([\\*?\[\]])", r"\\\1", name)
                lines.append(json.dumps(pattern, ensure_ascii=False) + " filter=lfs diff=lfs merge=lfs -text\n")
        return "".join(lines)

    def check(self):
        files = self.repository.retrieve_files()
        mismatches = [name for name, size, is_pointer in files if is_pointer != (size > THRESHOLD)]
        if mismatches:
            raise ValueError(
                f"Apply the 100 MiB LFS policy to {len(mismatches)} staged files with "
                "python scripts/lfs_policy.py sync:\n" + "\n".join(mismatches[:10])
            )
        attributes = self.repository.git("show", ":.gitattributes").decode("utf-8")
        if attributes != self.retrieve_attributes(files):
            raise ValueError("Refresh staged LFS paths with python scripts/lfs_policy.py sync.")
        print(f"LFS policy verified for {len(files)} staged files.")

    def sync(self):
        # Renormalization reads the working tree, so require it to match the index.
        subprocess.run(
            ["git", "diff", "--exit-code", "--quiet"],
            cwd=self.repository.root, check=True,
        )
        files = self.repository.retrieve_files()
        for name, size, is_pointer in files:
            if is_pointer and size <= THRESHOLD:
                path = self.repository.root / name
                if (not path.is_file() or path.stat().st_size != size
                        or (size < 1024 and POINTER.fullmatch(path.read_bytes()))):
                    raise ValueError(f"Hydrate {name} with git lfs pull before synchronization.")
        attributes = self.repository.root / ".gitattributes"
        attributes.write_text(self.retrieve_attributes(files), encoding="utf-8", newline="\n")
        self.repository.git("add", ".gitattributes")
        self.repository.git("add", "--renormalize", ".")
        self.check()

    def install_hook(self):
        location = self.repository.git("rev-parse", "--git-path", "hooks/pre-commit").decode().strip()
        path = self.repository.root / location
        if path.exists() and path.read_text() != HOOK:
            raise ValueError(f"Integrate python scripts/lfs_policy.py check into the existing hook: {path}")
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(HOOK, encoding="utf-8", newline="\n")
        path.chmod(path.stat().st_mode | 0o111)
        print(f"Installed LFS policy check: {path}")


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("command", choices=("check", "sync", "install-hook"))
    arguments = parser.parse_args()
    policy = LfsPolicy(Repository(Path.cwd()))
    try:
        if arguments.command == "sync":
            policy.sync()
        elif arguments.command == "install-hook":
            policy.install_hook()
        else:
            policy.check()
    except (ValueError, subprocess.CalledProcessError) as error:
        parser.exit(1, f"{error}\nStage desired working tree changes before running sync.\n")


if __name__ == "__main__":
    main()
